package com.manageeasy.me.Models;

import java.util.Date;

public class Characters {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column characters.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column characters.c_name
     *
     * @mbg.generated
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column characters.c_regTime
     *
     * @mbg.generated
     */
    private Date cRegtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column characters.c_upTime
     *
     * @mbg.generated
     */
    private Date cUptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column characters.c_desc
     *
     * @mbg.generated
     */
    private String cDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column characters.c_comment
     *
     * @mbg.generated
     */
    private String cComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column characters.c_id
     *
     * @return the value of characters.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column characters.c_id
     *
     * @param cId the value for characters.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column characters.c_name
     *
     * @return the value of characters.c_name
     *
     * @mbg.generated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column characters.c_name
     *
     * @param cName the value for characters.c_name
     *
     * @mbg.generated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column characters.c_regTime
     *
     * @return the value of characters.c_regTime
     *
     * @mbg.generated
     */
    public Date getcRegtime() {
        return cRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column characters.c_regTime
     *
     * @param cRegtime the value for characters.c_regTime
     *
     * @mbg.generated
     */
    public void setcRegtime(Date cRegtime) {
        this.cRegtime = cRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column characters.c_upTime
     *
     * @return the value of characters.c_upTime
     *
     * @mbg.generated
     */
    public Date getcUptime() {
        return cUptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column characters.c_upTime
     *
     * @param cUptime the value for characters.c_upTime
     *
     * @mbg.generated
     */
    public void setcUptime(Date cUptime) {
        this.cUptime = cUptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column characters.c_desc
     *
     * @return the value of characters.c_desc
     *
     * @mbg.generated
     */
    public String getcDesc() {
        return cDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column characters.c_desc
     *
     * @param cDesc the value for characters.c_desc
     *
     * @mbg.generated
     */
    public void setcDesc(String cDesc) {
        this.cDesc = cDesc == null ? null : cDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column characters.c_comment
     *
     * @return the value of characters.c_comment
     *
     * @mbg.generated
     */
    public String getcComment() {
        return cComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column characters.c_comment
     *
     * @param cComment the value for characters.c_comment
     *
     * @mbg.generated
     */
    public void setcComment(String cComment) {
        this.cComment = cComment == null ? null : cComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table characters
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cId=").append(cId);
        sb.append(", cName=").append(cName);
        sb.append(", cRegtime=").append(cRegtime);
        sb.append(", cUptime=").append(cUptime);
        sb.append(", cDesc=").append(cDesc);
        sb.append(", cComment=").append(cComment);
        sb.append("]");
        return sb.toString();
    }
}