package com.manageeasy.me.Models;

public class Departments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.d_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.d_name
     *
     * @mbg.generated
     */
    private String dName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.d_id
     *
     * @return the value of departments.d_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.d_id
     *
     * @param dId the value for departments.d_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.d_name
     *
     * @return the value of departments.d_name
     *
     * @mbg.generated
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.d_name
     *
     * @param dName the value for departments.d_name
     *
     * @mbg.generated
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dId=").append(dId);
        sb.append(", dName=").append(dName);
        sb.append("]");
        return sb.toString();
    }
}