package com.manageeasy.me.Models;

import java.util.Date;

public class Messages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.m_id
     *
     * @mbg.generated
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.m_time
     *
     * @mbg.generated
     */
    private Date mTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.mt_id
     *
     * @mbg.generated
     */
    private Integer mtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column messages.m_content
     *
     * @mbg.generated
     */
    private String mContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.m_id
     *
     * @return the value of messages.m_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.m_id
     *
     * @param mId the value for messages.m_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.m_time
     *
     * @return the value of messages.m_time
     *
     * @mbg.generated
     */
    public Date getmTime() {
        return mTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.m_time
     *
     * @param mTime the value for messages.m_time
     *
     * @mbg.generated
     */
    public void setmTime(Date mTime) {
        this.mTime = mTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.mt_id
     *
     * @return the value of messages.mt_id
     *
     * @mbg.generated
     */
    public Integer getMtId() {
        return mtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.mt_id
     *
     * @param mtId the value for messages.mt_id
     *
     * @mbg.generated
     */
    public void setMtId(Integer mtId) {
        this.mtId = mtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column messages.m_content
     *
     * @return the value of messages.m_content
     *
     * @mbg.generated
     */
    public String getmContent() {
        return mContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column messages.m_content
     *
     * @param mContent the value for messages.m_content
     *
     * @mbg.generated
     */
    public void setmContent(String mContent) {
        this.mContent = mContent == null ? null : mContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messages
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mId=").append(mId);
        sb.append(", mTime=").append(mTime);
        sb.append(", mtId=").append(mtId);
        sb.append(", mContent=").append(mContent);
        sb.append("]");
        return sb.toString();
    }
}