package com.manageeasy.me.Models;

public class Notificationtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationtype.nt_id
     *
     * @mbg.generated
     */
    private Integer ntId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notificationtype.nt_type
     *
     * @mbg.generated
     */
    private String ntType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationtype.nt_id
     *
     * @return the value of notificationtype.nt_id
     *
     * @mbg.generated
     */
    public Integer getNtId() {
        return ntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationtype.nt_id
     *
     * @param ntId the value for notificationtype.nt_id
     *
     * @mbg.generated
     */
    public void setNtId(Integer ntId) {
        this.ntId = ntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notificationtype.nt_type
     *
     * @return the value of notificationtype.nt_type
     *
     * @mbg.generated
     */
    public String getNtType() {
        return ntType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notificationtype.nt_type
     *
     * @param ntType the value for notificationtype.nt_type
     *
     * @mbg.generated
     */
    public void setNtType(String ntType) {
        this.ntType = ntType == null ? null : ntType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ntId=").append(ntId);
        sb.append(", ntType=").append(ntType);
        sb.append("]");
        return sb.toString();
    }
}