package com.manageeasy.me.Models;

import java.util.Date;

public class Notifications {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.n_id
     *
     * @mbg.generated
     */
    private Integer nId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.n_title
     *
     * @mbg.generated
     */
    private String nTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.pt_id
     *
     * @mbg.generated
     */
    private Integer ptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.n_deadline
     *
     * @mbg.generated
     */
    private Date nDeadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.n_files
     *
     * @mbg.generated
     */
    private String nFiles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.n_regTime
     *
     * @mbg.generated
     */
    private Date nRegtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.n_upTime
     *
     * @mbg.generated
     */
    private Date nUptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.nt_id
     *
     * @mbg.generated
     */
    private Integer ntId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.n_content
     *
     * @mbg.generated
     */
    private String nContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.n_comment
     *
     * @mbg.generated
     */
    private String nComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.n_id
     *
     * @return the value of notifications.n_id
     *
     * @mbg.generated
     */
    public Integer getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.n_id
     *
     * @param nId the value for notifications.n_id
     *
     * @mbg.generated
     */
    public void setnId(Integer nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.n_title
     *
     * @return the value of notifications.n_title
     *
     * @mbg.generated
     */
    public String getnTitle() {
        return nTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.n_title
     *
     * @param nTitle the value for notifications.n_title
     *
     * @mbg.generated
     */
    public void setnTitle(String nTitle) {
        this.nTitle = nTitle == null ? null : nTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.pt_id
     *
     * @return the value of notifications.pt_id
     *
     * @mbg.generated
     */
    public Integer getPtId() {
        return ptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.pt_id
     *
     * @param ptId the value for notifications.pt_id
     *
     * @mbg.generated
     */
    public void setPtId(Integer ptId) {
        this.ptId = ptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.n_deadline
     *
     * @return the value of notifications.n_deadline
     *
     * @mbg.generated
     */
    public Date getnDeadline() {
        return nDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.n_deadline
     *
     * @param nDeadline the value for notifications.n_deadline
     *
     * @mbg.generated
     */
    public void setnDeadline(Date nDeadline) {
        this.nDeadline = nDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.n_files
     *
     * @return the value of notifications.n_files
     *
     * @mbg.generated
     */
    public String getnFiles() {
        return nFiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.n_files
     *
     * @param nFiles the value for notifications.n_files
     *
     * @mbg.generated
     */
    public void setnFiles(String nFiles) {
        this.nFiles = nFiles == null ? null : nFiles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.n_regTime
     *
     * @return the value of notifications.n_regTime
     *
     * @mbg.generated
     */
    public Date getnRegtime() {
        return nRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.n_regTime
     *
     * @param nRegtime the value for notifications.n_regTime
     *
     * @mbg.generated
     */
    public void setnRegtime(Date nRegtime) {
        this.nRegtime = nRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.n_upTime
     *
     * @return the value of notifications.n_upTime
     *
     * @mbg.generated
     */
    public Date getnUptime() {
        return nUptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.n_upTime
     *
     * @param nUptime the value for notifications.n_upTime
     *
     * @mbg.generated
     */
    public void setnUptime(Date nUptime) {
        this.nUptime = nUptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.nt_id
     *
     * @return the value of notifications.nt_id
     *
     * @mbg.generated
     */
    public Integer getNtId() {
        return ntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.nt_id
     *
     * @param ntId the value for notifications.nt_id
     *
     * @mbg.generated
     */
    public void setNtId(Integer ntId) {
        this.ntId = ntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.n_content
     *
     * @return the value of notifications.n_content
     *
     * @mbg.generated
     */
    public String getnContent() {
        return nContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.n_content
     *
     * @param nContent the value for notifications.n_content
     *
     * @mbg.generated
     */
    public void setnContent(String nContent) {
        this.nContent = nContent == null ? null : nContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.n_comment
     *
     * @return the value of notifications.n_comment
     *
     * @mbg.generated
     */
    public String getnComment() {
        return nComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.n_comment
     *
     * @param nComment the value for notifications.n_comment
     *
     * @mbg.generated
     */
    public void setnComment(String nComment) {
        this.nComment = nComment == null ? null : nComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nId=").append(nId);
        sb.append(", nTitle=").append(nTitle);
        sb.append(", ptId=").append(ptId);
        sb.append(", nDeadline=").append(nDeadline);
        sb.append(", nFiles=").append(nFiles);
        sb.append(", nRegtime=").append(nRegtime);
        sb.append(", nUptime=").append(nUptime);
        sb.append(", ntId=").append(ntId);
        sb.append(", nContent=").append(nContent);
        sb.append(", nComment=").append(nComment);
        sb.append("]");
        return sb.toString();
    }
}