package com.manageeasy.me.Models;

public class Projectlevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectlevel.pl_id
     *
     * @mbg.generated
     */
    private Integer plId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectlevel.pl_name
     *
     * @mbg.generated
     */
    private String plName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectlevel.pl_id
     *
     * @return the value of projectlevel.pl_id
     *
     * @mbg.generated
     */
    public Integer getPlId() {
        return plId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectlevel.pl_id
     *
     * @param plId the value for projectlevel.pl_id
     *
     * @mbg.generated
     */
    public void setPlId(Integer plId) {
        this.plId = plId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectlevel.pl_name
     *
     * @return the value of projectlevel.pl_name
     *
     * @mbg.generated
     */
    public String getPlName() {
        return plName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectlevel.pl_name
     *
     * @param plName the value for projectlevel.pl_name
     *
     * @mbg.generated
     */
    public void setPlName(String plName) {
        this.plName = plName == null ? null : plName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectlevel
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", plId=").append(plId);
        sb.append(", plName=").append(plName);
        sb.append("]");
        return sb.toString();
    }
}