package com.manageeasy.me.Models;

public class Projecttype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projecttype.pt_id
     *
     * @mbg.generated
     */
    private Integer ptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projecttype.pt_name
     *
     * @mbg.generated
     */
    private String ptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projecttype.pt_id
     *
     * @return the value of projecttype.pt_id
     *
     * @mbg.generated
     */
    public Integer getPtId() {
        return ptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projecttype.pt_id
     *
     * @param ptId the value for projecttype.pt_id
     *
     * @mbg.generated
     */
    public void setPtId(Integer ptId) {
        this.ptId = ptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projecttype.pt_name
     *
     * @return the value of projecttype.pt_name
     *
     * @mbg.generated
     */
    public String getPtName() {
        return ptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projecttype.pt_name
     *
     * @param ptName the value for projecttype.pt_name
     *
     * @mbg.generated
     */
    public void setPtName(String ptName) {
        this.ptName = ptName == null ? null : ptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projecttype
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ptId=").append(ptId);
        sb.append(", ptName=").append(ptName);
        sb.append("]");
        return sb.toString();
    }
}