package com.manageeasy.me.Models;

import java.util.Date;

public class Projects {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.pt_id
     *
     * @mbg.generated
     */
    private Integer ptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.pl_id
     *
     * @mbg.generated
     */
    private Integer plId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.p_name
     *
     * @mbg.generated
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.p_start
     *
     * @mbg.generated
     */
    private Date pStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.p_end
     *
     * @mbg.generated
     */
    private Date pEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.u_id
     *
     * @mbg.generated
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.u_phone
     *
     * @mbg.generated
     */
    private String uPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.u_email
     *
     * @mbg.generated
     */
    private String uEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.ma_id
     *
     * @mbg.generated
     */
    private Integer maId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.de_file
     *
     * @mbg.generated
     */
    private String deFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.pr_file
     *
     * @mbg.generated
     */
    private String prFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.me_file
     *
     * @mbg.generated
     */
    private String meFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.fi_file
     *
     * @mbg.generated
     */
    private String fiFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.p_state
     *
     * @mbg.generated
     */
    private Integer pState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.f_reason
     *
     * @mbg.generated
     */
    private String fReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.p_id
     *
     * @return the value of projects.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.p_id
     *
     * @param pId the value for projects.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.pt_id
     *
     * @return the value of projects.pt_id
     *
     * @mbg.generated
     */
    public Integer getPtId() {
        return ptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.pt_id
     *
     * @param ptId the value for projects.pt_id
     *
     * @mbg.generated
     */
    public void setPtId(Integer ptId) {
        this.ptId = ptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.pl_id
     *
     * @return the value of projects.pl_id
     *
     * @mbg.generated
     */
    public Integer getPlId() {
        return plId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.pl_id
     *
     * @param plId the value for projects.pl_id
     *
     * @mbg.generated
     */
    public void setPlId(Integer plId) {
        this.plId = plId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.p_name
     *
     * @return the value of projects.p_name
     *
     * @mbg.generated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.p_name
     *
     * @param pName the value for projects.p_name
     *
     * @mbg.generated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.p_start
     *
     * @return the value of projects.p_start
     *
     * @mbg.generated
     */
    public Date getpStart() {
        return pStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.p_start
     *
     * @param pStart the value for projects.p_start
     *
     * @mbg.generated
     */
    public void setpStart(Date pStart) {
        this.pStart = pStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.p_end
     *
     * @return the value of projects.p_end
     *
     * @mbg.generated
     */
    public Date getpEnd() {
        return pEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.p_end
     *
     * @param pEnd the value for projects.p_end
     *
     * @mbg.generated
     */
    public void setpEnd(Date pEnd) {
        this.pEnd = pEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.u_id
     *
     * @return the value of projects.u_id
     *
     * @mbg.generated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.u_id
     *
     * @param uId the value for projects.u_id
     *
     * @mbg.generated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.u_phone
     *
     * @return the value of projects.u_phone
     *
     * @mbg.generated
     */
    public String getuPhone() {
        return uPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.u_phone
     *
     * @param uPhone the value for projects.u_phone
     *
     * @mbg.generated
     */
    public void setuPhone(String uPhone) {
        this.uPhone = uPhone == null ? null : uPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.u_email
     *
     * @return the value of projects.u_email
     *
     * @mbg.generated
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.u_email
     *
     * @param uEmail the value for projects.u_email
     *
     * @mbg.generated
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail == null ? null : uEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.ma_id
     *
     * @return the value of projects.ma_id
     *
     * @mbg.generated
     */
    public Integer getMaId() {
        return maId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.ma_id
     *
     * @param maId the value for projects.ma_id
     *
     * @mbg.generated
     */
    public void setMaId(Integer maId) {
        this.maId = maId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.de_file
     *
     * @return the value of projects.de_file
     *
     * @mbg.generated
     */
    public String getDeFile() {
        return deFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.de_file
     *
     * @param deFile the value for projects.de_file
     *
     * @mbg.generated
     */
    public void setDeFile(String deFile) {
        this.deFile = deFile == null ? null : deFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.pr_file
     *
     * @return the value of projects.pr_file
     *
     * @mbg.generated
     */
    public String getPrFile() {
        return prFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.pr_file
     *
     * @param prFile the value for projects.pr_file
     *
     * @mbg.generated
     */
    public void setPrFile(String prFile) {
        this.prFile = prFile == null ? null : prFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.me_file
     *
     * @return the value of projects.me_file
     *
     * @mbg.generated
     */
    public String getMeFile() {
        return meFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.me_file
     *
     * @param meFile the value for projects.me_file
     *
     * @mbg.generated
     */
    public void setMeFile(String meFile) {
        this.meFile = meFile == null ? null : meFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.fi_file
     *
     * @return the value of projects.fi_file
     *
     * @mbg.generated
     */
    public String getFiFile() {
        return fiFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.fi_file
     *
     * @param fiFile the value for projects.fi_file
     *
     * @mbg.generated
     */
    public void setFiFile(String fiFile) {
        this.fiFile = fiFile == null ? null : fiFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.p_state
     *
     * @return the value of projects.p_state
     *
     * @mbg.generated
     */
    public Integer getpState() {
        return pState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.p_state
     *
     * @param pState the value for projects.p_state
     *
     * @mbg.generated
     */
    public void setpState(Integer pState) {
        this.pState = pState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.f_reason
     *
     * @return the value of projects.f_reason
     *
     * @mbg.generated
     */
    public String getfReason() {
        return fReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.f_reason
     *
     * @param fReason the value for projects.f_reason
     *
     * @mbg.generated
     */
    public void setfReason(String fReason) {
        this.fReason = fReason == null ? null : fReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pId=").append(pId);
        sb.append(", ptId=").append(ptId);
        sb.append(", plId=").append(plId);
        sb.append(", pName=").append(pName);
        sb.append(", pStart=").append(pStart);
        sb.append(", pEnd=").append(pEnd);
        sb.append(", uId=").append(uId);
        sb.append(", uPhone=").append(uPhone);
        sb.append(", uEmail=").append(uEmail);
        sb.append(", maId=").append(maId);
        sb.append(", deFile=").append(deFile);
        sb.append(", prFile=").append(prFile);
        sb.append(", meFile=").append(meFile);
        sb.append(", fiFile=").append(fiFile);
        sb.append(", pState=").append(pState);
        sb.append(", fReason=").append(fReason);
        sb.append("]");
        return sb.toString();
    }
}