package com.manageeasy.me.Models;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_id
     *
     * @mbg.generated
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_name
     *
     * @mbg.generated
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_password
     *
     * @mbg.generated
     */
    private String uPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_regTime
     *
     * @mbg.generated
     */
    private Date uRegtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_upTime
     *
     * @mbg.generated
     */
    private Date uUptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.d_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.u_comment
     *
     * @mbg.generated
     */
    private String uComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_id
     *
     * @return the value of users.u_id
     *
     * @mbg.generated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_id
     *
     * @param uId the value for users.u_id
     *
     * @mbg.generated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_name
     *
     * @return the value of users.u_name
     *
     * @mbg.generated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_name
     *
     * @param uName the value for users.u_name
     *
     * @mbg.generated
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_password
     *
     * @return the value of users.u_password
     *
     * @mbg.generated
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_password
     *
     * @param uPassword the value for users.u_password
     *
     * @mbg.generated
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword == null ? null : uPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_regTime
     *
     * @return the value of users.u_regTime
     *
     * @mbg.generated
     */
    public Date getuRegtime() {
        return uRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_regTime
     *
     * @param uRegtime the value for users.u_regTime
     *
     * @mbg.generated
     */
    public void setuRegtime(Date uRegtime) {
        this.uRegtime = uRegtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_upTime
     *
     * @return the value of users.u_upTime
     *
     * @mbg.generated
     */
    public Date getuUptime() {
        return uUptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_upTime
     *
     * @param uUptime the value for users.u_upTime
     *
     * @mbg.generated
     */
    public void setuUptime(Date uUptime) {
        this.uUptime = uUptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.c_id
     *
     * @return the value of users.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.c_id
     *
     * @param cId the value for users.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.d_id
     *
     * @return the value of users.d_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.d_id
     *
     * @param dId the value for users.d_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.u_comment
     *
     * @return the value of users.u_comment
     *
     * @mbg.generated
     */
    public String getuComment() {
        return uComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.u_comment
     *
     * @param uComment the value for users.u_comment
     *
     * @mbg.generated
     */
    public void setuComment(String uComment) {
        this.uComment = uComment == null ? null : uComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uId=").append(uId);
        sb.append(", uName=").append(uName);
        sb.append(", uPassword=").append(uPassword);
        sb.append(", uRegtime=").append(uRegtime);
        sb.append(", uUptime=").append(uUptime);
        sb.append(", cId=").append(cId);
        sb.append(", dId=").append(dId);
        sb.append(", uComment=").append(uComment);
        sb.append("]");
        return sb.toString();
    }
}