package com.manageeasy.me.Daos;

import com.manageeasy.me.Models.Characters;
import java.util.List;

public interface CharactersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table characters
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table characters
     *
     * @mbg.generated
     * @param record
     */
    int insert(Characters record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table characters
     *
     * @mbg.generated
     */
    Characters selectByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table characters
     *
     * @mbg.generated
     */
    List<Characters> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table characters
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Characters record);

    /**
     * 根据备注筛选
     */
    List<Characters> selectByComment(String cComment);
}