package com.manageeasy.me.Daos;

import com.manageeasy.me.Models.Judge;
import java.util.List;

public interface JudgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer jId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge
     *
     * @mbg.generated
     */
    int insert(Judge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge
     *
     * @mbg.generated
     */
    Judge selectByPrimaryKey(Integer jId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge
     *
     * @mbg.generated
     */
    List<Judge> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Judge record);

    /**
     * select by project state
     */
    List<Judge> selectByState(int state, int ptid);
}