package com.manageeasy.me.Daos;

import com.manageeasy.me.Models.Majortype;
import java.util.List;

public interface MajortypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majortype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer maId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majortype
     *
     * @mbg.generated
     */
    int insert(Majortype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majortype
     *
     * @mbg.generated
     */
    Majortype selectByPrimaryKey(Integer maId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majortype
     *
     * @mbg.generated
     */
    List<Majortype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table majortype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Majortype record);
}