package com.manageeasy.me.Daos;

import com.manageeasy.me.Models.Notificationtype;
import java.util.List;

public interface NotificationtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ntId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbg.generated
     */
    int insert(Notificationtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbg.generated
     */
    Notificationtype selectByPrimaryKey(Integer ntId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbg.generated
     */
    List<Notificationtype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notificationtype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Notificationtype record);
}