package com.manageeasy.me.Daos;

import com.manageeasy.me.Models.Notifications;
import java.util.List;

public interface NotificationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbg.generated
     */
    int insert(Notifications record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbg.generated
     */
    Notifications selectByPrimaryKey(Integer nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbg.generated
     */
    List<Notifications> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notifications
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Notifications record);
}