package com.manageeasy.me.Daos;

import com.manageeasy.me.Models.Projects;
import java.util.List;

public interface ProjectsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated
     */
    int insert(Projects record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated
     */
    Projects selectByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated
     */
    List<Projects> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Projects record);

    /**
     * select by state and project type and user id
     */
    List<Projects> selectByUSPt(int uid, int pState, int ptId);

    /**
     * select by state and project type
     */
    List<Projects> selectBySPt(int pState, int ptId);

    /**
     * select by name, level, user id
     */
    Projects selectByNULv(int level, int uid, String name);
}