package com.manageeasy.me.Daos;

import com.manageeasy.me.Models.Projecttype;
import java.util.List;

public interface ProjecttypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projecttype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projecttype
     *
     * @mbg.generated
     */
    int insert(Projecttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projecttype
     *
     * @mbg.generated
     */
    Projecttype selectByPrimaryKey(Integer ptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projecttype
     *
     * @mbg.generated
     */
    List<Projecttype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projecttype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Projecttype record);
}